# -*- coding: utf-8 -*-
"""Stability_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYgFrcg7nGUZXLL3-RnjUVBNvLN_9ruO
"""

#DYNAMIC MODES OF STABILITY
#AUTHOR: MONISHA VIJAYAN(AE25M037)
from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np

D2R = np.pi / 180.0


@dataclass
class UAVInputs:
    S:float = 0.53
    b:float = 2.00
    c_bar:float = 0.27
    AR: float = 7.5372
    m: float = 6.30
    g: float = 9.81
    Ixx: float = 0.75
    Iyy: float = 0.38
    Izz: float = 1.05
    rho: float = 1.22
    a_sound: float = 340.0
    CD0:float = 0.02873
    e: float = 1.00
    CLalpha_w:  float = 3.133
    CLalpha_t:  float = 4.329
    CLalpha_v: float = 2.685
    CLalpha_ac: float = 3.9210
    S_t: float = 0.13
    l_t: float = 0.70
    AR_t: float = 4.5
    S_v: float = 0.05
    l_v: float = 0.70
    AR_v: float = 1.5
    eta_t: float = 0.99
    eta_v: float = 0.95
    Cm_alpha: float = -0.4176
    Cm_q1: float = -14.9384
    CL_q1: float = 5.6584
    CD_alpha:float = 0.1040
    CD_q1: float = 0.1500
    CL_Ma: float = 0.0229
    CD_Ma: float = 0.0
    V_trim_ref: float = 24.658
    CL_trim_ref:float = 0.3139
    alpha_trim_ref_deg: float = 2.16
    D_f:  float = 0.30
    z_w:  float = 0.00
    Gamma_deg: float = 0.0
    Lambda_c4_deg: float = 0.0


def print_section(title: str) -> None:
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


def eigenvalue_plot(evals: np.ndarray, title: str, filename: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.axhline(0, linewidth=0.8, color='k')
    ax.axvline(0, linewidth=0.8, color='k')

    for ev in evals:
        is_complex = abs(ev.imag) > 1e-6
        ax.scatter(ev.real, ev.imag, s=90,
                   color='tab:orange' if is_complex else 'tab:blue',
                   marker='o' if is_complex else 'D', zorder=5)

    ax.legend(handles=[
        Line2D([0],[0], marker='D', color='w', markerfacecolor='tab:blue',
               markersize=9, label='Real root'),
        Line2D([0],[0], marker='o', color='w', markerfacecolor='tab:orange',
               markersize=9, label='Complex pair'),
    ], fontsize=8)

    for i, ev in enumerate(evals, 1):
        ax.annotate(f"λ{i}", (ev.real, ev.imag),
                    textcoords="offset points", xytext=(6, 5), fontsize=9)

    ax.set_xlabel("Real (1/s)")
    ax.set_ylabel("Imag (1/s)")
    ax.set_title(title)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(filename, dpi=200)
    plt.close(fig)


def plot_longitudinal_eigenvalues(long: Dict, filename: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.axhline(0, linewidth=0.8, color='k')
    ax.axvline(0, linewidth=0.8, color='k')

    for ev in long["evals_sp2"]:
        ax.scatter(ev.real, ev.imag, s=100, color='tab:red', marker='*', zorder=5)
    for ev in long["ph_roots"]:
        ax.scatter(ev.real, ev.imag, s=80, color='tab:orange', zorder=5)

    ax.set_xlabel("Real (1/s)")
    ax.set_ylabel("Imag (1/s)")
    ax.set_title("Longitudinal eigenvalues")
    ax.grid(True, alpha=0.3)
    ax.legend(handles=[
        Line2D([0],[0], marker='*', color='w', markerfacecolor='tab:red',
               markersize=11, label='Short-period'),
        Line2D([0],[0], marker='o', color='w', markerfacecolor='tab:orange',
               markersize=9, label='Phugoid'),
    ], fontsize=8)

    fig.tight_layout()
    fig.savefig(filename, dpi=200)
    plt.close(fig)


def compute_longitudinal(inp: UAVInputs) -> Dict:
    print_section("LONGITUDINAL STABILITY")

    V_trim  = inp.V_trim_ref
    CL_trim = inp.CL_trim_ref
    alpha_t = inp.alpha_trim_ref_deg * D2R
    K       = 1.0 / (math.pi * inp.AR * inp.e)
    CD_trim = inp.CD0 + K * CL_trim ** 2
    q_trim  = 0.5 * inp.rho * V_trim ** 2
    Ma_trim = V_trim / inp.a_sound
    T_req   = q_trim * inp.S * CD_trim
    P_req   = T_req * V_trim

    qSc_Iyy = q_trim * inp.S * inp.c_bar / inp.Iyy
    qS_W    = q_trim * inp.S / (inp.m * inp.g)
    g_V     = inp.g / V_trim
    c_2V    = inp.c_bar / (2.0 * V_trim)

    print(f"alpha_trim = {inp.alpha_trim_ref_deg:.3f} deg")
    print(f"CL_trim = {CL_trim:.4f}")
    print(f"V_trim  = {V_trim:.3f} m/s")
    print(f"Ma_trim = {Ma_trim:.5f}")
    print(f"CD_trim = {CD_trim:.5f}")
    print(f"Thrust = {T_req:.2f} N")
    print(f"Power  = {P_req:.2f} W")
    print(f"\nqSc/Iyy = {qSc_Iyy:.4f}")
    print(f"qS/W  = {qS_W:.4f}")
    print(f"g/V  = {g_V:.4f}")
    print(f"c/(2V)  = {c_2V:.6f}")

    Za_V  = qS_W * g_V * inp.CLalpha_ac
    M_alp = qSc_Iyy * inp.Cm_alpha
    M_q   = qSc_Iyy * inp.Cm_q1 * c_2V

    A_SP_2 = np.array([[-Za_V, 1.0],
                        [M_alp, M_q]])

    evals_sp2  = np.linalg.eigvals(A_SP_2)
    sp_ev      = evals_sp2[0]
    wn_SP      = abs(sp_ev)
    zeta_SP    = -sp_ev.real / wn_SP if abs(sp_ev.imag) > 1e-8 else sp_ev.real / wn_SP

    print(f"\nSHORT-PERIOD (2x2 reduced system)")
    print(f"  A_SP =\n{np.array2string(A_SP_2, precision=4)}")
    print(f"  eigenvalues : {evals_sp2[0].real:+.4f} ± j{abs(evals_sp2[0].imag):.4f}")
    print(f"  wn_SP = {wn_SP:.4f} rad/s")
    print(f"  zeta_SP = {zeta_SP:.4f}")
    print(f"  T_SP  = {2*math.pi/wn_SP:.4f} s")

    wn_Ph_sq    = (g_V**2) * qS_W * (Ma_trim * inp.CL_Ma + 2.0 * CL_trim)
    wn_Ph       = math.sqrt(max(wn_Ph_sq, 1e-12))
    zeta_Ph     = (g_V * qS_W * 2.0 * CD_trim) / (2.0 * wn_Ph)

    print(f"\nPHUGOID (2nd-order approximation)")
    print(f"  wn_Ph   = {wn_Ph:.4f} rad/s")
    print(f"  zeta_Ph = {zeta_Ph:.4f}")
    print(f"  T_Ph    = {2*math.pi/wn_Ph:.2f} s")

    k0  = 1.0 + g_V * qS_W * inp.CL_q1 * c_2V
    fac = Ma_trim * inp.CL_Ma + 2.0 * CL_trim

    a11 = -g_V * qS_W * (Ma_trim * inp.CD_Ma + 2.0 * CD_trim)
    a12 = -g_V
    a13 = -g_V * qS_W * inp.CD_alpha
    a14 = -g_V * qS_W * inp.CD_q1 * c_2V
    a21 =  g_V * qS_W * fac
    a22 =  0.0
    a23 =  g_V * qS_W * inp.CLalpha_ac
    a24 =  g_V * qS_W * inp.CL_q1 * c_2V
    a43 = (((g_V**2)*(qS_W**2)*fac*inp.CD_alpha) + qSc_Iyy*inp.Cm_alpha) / k0
    a44 = (qSc_Iyy*c_2V*inp.Cm_q1 - g_V*qS_W*inp.CLalpha_ac
           + (g_V**2)*(qS_W**2)*inp.CD_q1*c_2V*fac) / k0
    a41 = (g_V**2)*(qS_W**2)*fac*(Ma_trim*inp.CD_Ma+2*CD_trim) / k0
    a42 = (g_V**2)*qS_W*fac / k0

    A_long = np.array([
        [a11, a12, a13, a14],
        [a21, a22, a23, a24],
        [0.0, 0.0, 0.0, 1.0],
        [a41, a42, a43, a44],
    ])

    print(f"\nFULL 4x4 A-MATRIX")
    print(np.array2string(A_long, precision=4, suppress_small=True))

    evals_long, evecs_long = np.linalg.eig(A_long)
    state_names = ["dV/V", "dgamma", "dalpha", "dalpha_dot"]

    print(f"\nFull 4x4 eigenvalues:")
    for i, (ev, vec) in enumerate(zip(evals_long, evecs_long.T), 1):
        dom = np.argmax(np.abs(vec))
        print(f"  lambda{i}: {ev.real:+.5f}{ev.imag:+.5f}j  dominant: {state_names[dom]}")

    sp_roots = [ev for ev, vec in zip(evals_long, evecs_long.T)
                if np.argmax(np.abs(vec)) >= 2]
    ph_roots = [ev for ev, vec in zip(evals_long, evecs_long.T)
                if np.argmax(np.abs(vec)) < 2]

    print(f"\nSP roots (4x4):")
    for ev in sp_roots:
        print(f"  {ev.real:+.4f}{ev.imag:+.4f}j")

    print(f"\nPhugoid roots (4x4):")
    for ev in ph_roots:
        wn = abs(ev)
        zeta = -ev.real / wn if wn > 1e-8 else 0.0
        print(f"  {ev.real:+.5f}±j{abs(ev.imag):.5f}  wn={wn:.4f}  zeta={zeta:.4f}")

    return {
        "V_trim": V_trim, "q_trim": q_trim, "Ma_trim": Ma_trim,
        "CL_trim": CL_trim, "CD_trim": CD_trim, "alpha_trim": alpha_t,
        "qSc_Iyy": qSc_Iyy, "qS_W": qS_W, "g_V": g_V, "c_2V": c_2V, "K": K,
        "wn_SP": wn_SP, "zeta_SP": zeta_SP, "evals_sp2": evals_sp2,
        "wn_Ph": wn_Ph, "zeta_Ph": zeta_Ph,
        "A_long": A_long, "evals_long": evals_long,
        "sp_roots": sp_roots, "ph_roots": ph_roots,
        "CLalpha_ac": inp.CLalpha_ac,
    }


def compute_lateral(inp: UAVInputs, long: Dict) -> Dict:
    print_section("LATERAL-DIRECTIONAL STABILITY")

    V_trim  = long["V_trim"]
    q_trim  = long["q_trim"]
    g_V     = long["g_V"]
    CL_trim = long["CL_trim"]
    CD_trim = long["CD_trim"]
    CLalpha = long["CLalpha_ac"]
    alpha_t = long["alpha_trim"]

    Lambda_c4_rad = inp.Lambda_c4_deg * D2R
    Gamma_rad     = inp.Gamma_deg * D2R

    sidewash = (
        0.724
        + 3.06 * (inp.S_v / inp.S) / (1.0 + math.cos(Lambda_c4_rad))
        + 0.4 * inp.z_w / inp.D_f
        + 0.009 * inp.AR
    )

    CY_beta_VT = -(inp.eta_v * inp.CLalpha_v * (inp.S_v / inp.S) * sidewash)
    CY_beta    = -0.0001 * Gamma_rad + CY_beta_VT
    Cn_beta_VT = -CY_beta_VT * (inp.l_v / inp.b)
    Cn_beta    = -0.075 * Gamma_rad * CL_trim + Cn_beta_VT

    z_VT  = (4.0/9.0) * math.sqrt(inp.AR_v * inp.S_v)
    z_eff = z_VT * math.cos(alpha_t) - inp.l_v * math.sin(alpha_t)

    Cl_beta_VT = (z_eff / inp.b) * CY_beta_VT
    Cl_beta_w  = -(Gamma_rad * inp.CLalpha_w * inp.c_bar * inp.b) / (6.0 * inp.S)
    Cl_beta    = Cl_beta_w + Cl_beta_VT

    lVT_eff = inp.l_v * math.cos(alpha_t) + z_VT * math.sin(alpha_t)

    Cl_p2 = -1.0/6.0*(CLalpha + CD_trim) + 2.0*(z_eff/inp.b)*((z_eff-z_VT)/inp.b)*CY_beta_VT
    Cn_r1 = (2.0/inp.b**2) * lVT_eff**2 * CY_beta_VT
    Cl_r1 = CL_trim/3.0 - (2.0/inp.b**2)*lVT_eff*z_eff*CY_beta_VT
    Cn_r2 = -CD_trim/3.0
    Cl_r2 =  CL_trim/3.0

    qSb_Ixx = q_trim * inp.S * inp.b / inp.Ixx
    qSb_Izz = q_trim * inp.S * inp.b / inp.Izz
    qS_m    = q_trim * inp.S / inp.m
    b_2V    = inp.b / (2.0 * V_trim)

    N_beta = qSb_Izz * Cn_beta
    Y_beta = qS_m    * CY_beta
    L_beta = qSb_Ixx * Cl_beta
    L_p2   = qSb_Ixx * Cl_p2 * b_2V
    N_r1   = qSb_Izz * Cn_r1 * b_2V
    L_r1   = qSb_Ixx * Cl_r1 * b_2V
    N_r2   = qSb_Izz * Cn_r2 * b_2V
    L_r2   = qSb_Ixx * Cl_r2 * b_2V

    lambda_roll   = L_p2
    wn_DR_sq      = N_beta + g_V*(Y_beta*N_r2 + L_beta/lambda_roll)
    wn_DR         = math.sqrt(abs(wn_DR_sq))
    zeta_DR       = -(N_r1 + g_V*(Y_beta + L_r1/lambda_roll)) / (2.0*wn_DR)
    lambda_spiral = g_V*(L_beta*N_r2 - N_beta*L_r2)/(lambda_roll*wn_DR_sq)

    A_lat = np.array([
        [0.0,       1.0,  0.0,                        0.0],
        [g_V*L_r2,  L_p2, L_beta+g_V*Y_beta*L_r2,   -L_r1],
        [0.0,       0.0,  0.0,                        1.0],
        [-g_V*N_r2, g_V,  -(N_beta+g_V*Y_beta*N_r2), N_r1+g_V*Y_beta],
    ])

    evals_lat = np.linalg.eigvals(A_lat)

    print(f"sidewash  = {sidewash:.4f}")
    print(f"CY_beta   = {CY_beta:.5f}")
    print(f"Cn_beta   = {Cn_beta:.5f}")
    print(f"Cl_beta   = {Cl_beta:.5f}")
    print(f"\nN_beta = {N_beta:.4f}  Y_beta = {Y_beta:.4f}")
    print(f"L_beta = {L_beta:.4f}  L_p2   = {L_p2:.4f}")
    print(f"\nLateral A-matrix:")
    print(np.array2string(A_lat, precision=4, suppress_small=True))
    print(f"\nLateral eigenvalues:")
    for ev in evals_lat:
        print(f"  {ev.real:+.6f} {ev.imag:+.6f}j")

    print(f"\nLATERAL MODE SUMMARY")
    print(f"  Roll subsidence  lambda = {lambda_roll:+.4f} s-1")
    print(f"  Dutch roll       wn     = {wn_DR:.4f} rad/s")
    print(f"  Dutch roll       zeta   = {zeta_DR:.4f}")
    print(f"  Spiral           lambda = {lambda_spiral:+.5f} s-1  ({'UNSTABLE' if lambda_spiral > 0 else 'stable'})")

    return {
        "lambda_roll": lambda_roll, "wn_DR": wn_DR, "zeta_DR": zeta_DR,
        "lambda_spiral": lambda_spiral,
        "CY_beta": CY_beta, "Cn_beta": Cn_beta, "Cl_beta": Cl_beta,
        "A_lat": A_lat, "evals_lat": evals_lat,
    }


def main() -> None:
    inp  = UAVInputs()
    long = compute_longitudinal(inp)
    lat  = compute_lateral(inp, long)

    try:
        out_dir = Path(__file__).resolve().parent
    except NameError:
        out_dir = Path.cwd()

    plot_longitudinal_eigenvalues(long, out_dir / "longitudinal_eigenvalues.png")
    eigenvalue_plot(lat["evals_lat"], "Lateral-directional eigenvalues",
                    out_dir / "lateral_eigenvalues.png")

    print_section("SUMMARY")
    sp = long["evals_sp2"][0]
    print(f"Trim: V={long['V_trim']:.3f} m/s  CL={long['CL_trim']:.4f}  CD={long['CD_trim']:.5f}")
    print(f"\nSHORT-PERIOD")
    print(f"  lambda = {sp.real:+.4f} ± j{abs(sp.imag):.4f} s-1")
    print(f"  wn     = {long['wn_SP']:.4f} rad/s")
    print(f"  zeta   = {long['zeta_SP']:.4f}")
    print(f"  T      = {2*math.pi/long['wn_SP']:.4f} s")
    print(f"\nPHUGOID")
    ph = long["ph_roots"]
    if ph:
        p = ph[0]; wn = abs(p); zeta = -p.real/wn
        print(f"  lambda = {p.real:+.5f} ± j{abs(p.imag):.5f} s-1")
        print(f"  wn     = {wn:.4f} rad/s")
        print(f"  zeta   = {zeta:.4f}")
    print(f"\nLATERAL-DIRECTIONAL")
    print(f"  Roll subsidence  lambda = {lat['lambda_roll']:+.4f} s-1")
    print(f"  Dutch roll       wn     = {lat['wn_DR']:.4f} rad/s")
    print(f"  Dutch roll       zeta   = {lat['zeta_DR']:.4f}")
    print(f"  Spiral           lambda = {lat['lambda_spiral']:+.5f} s-1  ({'UNSTABLE' if lat['lambda_spiral'] > 0 else 'stable'})")


if __name__ == "__main__":
    main()